name: deploy.yaml

on:
  push:
    branches:
      - master

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: echo "Hello"
      - name: Pack
        run: |
          pwd
          ls -lga
          dotnet build -c Release